### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by balupton** [rauchg/slackin#102]
@rauchg we are using slackin for the bevry community - https://bevry.me - I've noticed that a few pull requests, as well as many issues have not been addressed. If you'd like, we (the bevry community) can take over maintenance of this project. I have experience maintaining about 200 npm packages already.

The easiest way would be it to be transferred to the bevry github org - https://github.com/bevry - that way we can manage github permissions easily with our community.

Let me know your thoughts.

**Comment by rauchg** [comment]
I'm happy with the surface the project covers. I merged a few minor PRs and now there're 3 left that need work on them. You can help comment on the many issues and PR without having push access.

**Comment by balupton** [comment]
sure, thanks
