### ISSUE TITLE
Permalink to a preselected channel

### ISSUE THREAD

**Issue by konklone** [rauchg/slackin#111]
It'd be nice to be able to link to a Slackin instance where it defaults to a particular channel in the dropdown. e.g., `chat.whatever.com/?channel=trees` would make `trees` the dropdown's selected channel.

**Comment by mattgorecki** [comment]
I opted for using a #hash on the URL like so: http://slack.tsi.io/#support

You can add the following to client.js:

```javascript
body.onload = function(){
  if(window.location.hash) {
    body.querySelector('select[name=channel]').value=window.location.hash.slice(1);
  }
};
```

**Comment by rauchg** [comment]
@mattgorecki that seems like a cool solution. I'd be down to merging that.
