### ISSUE TITLE
Having trouble installing on Ubuntu 14 LTS -- maybe related to gyp?

### ISSUE THREAD

**Issue by Suhail** [rauchg/slackin#128]
Any ideas what's the issue here?

~: npm install -g slackin
npm http GET https://registry.npmjs.org/slackin
npm http 304 https://registry.npmjs.org/slackin
npm WARN engine slackin@0.7.3: wanted: {"node":">=0.12.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/commander/2.6.0
npm http GET https://registry.npmjs.org/babel/4.7.1
npm http GET https://registry.npmjs.org/body-parser/1.10.2
npm http GET https://registry.npmjs.org/debug/2.1.1
npm http GET https://registry.npmjs.org/email-regex/1.0.0
npm http GET https://registry.npmjs.org/express/4.11.0
npm http GET https://registry.npmjs.org/hostenv/1.0.1
npm http GET https://registry.npmjs.org/opentype.js/0.4.4
npm http GET https://registry.npmjs.org/socket.io/1.3.6
npm http GET https://registry.npmjs.org/superagent/0.21.0
npm http GET https://registry.npmjs.org/vd/0.1.0
npm http 304 https://registry.npmjs.org/body-parser/1.10.2
npm http 304 https://registry.npmjs.org/babel/4.7.1
npm http 304 https://registry.npmjs.org/email-regex/1.0.0
npm http 304 https://registry.npmjs.org/debug/2.1.1
npm http 304 https://registry.npmjs.org/commander/2.6.0
npm http 304 https://registry.npmjs.org/express/4.11.0
npm http 304 https://registry.npmjs.org/hostenv/1.0.1
npm http 304 https://registry.npmjs.org/opentype.js/0.4.4
npm http 304 https://registry.npmjs.org/socket.io/1.3.6
npm http 304 https://registry.npmjs.org/superagent/0.21.0
npm http 304 https://registry.npmjs.org/vd/0.1.0
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/bytes/1.0.0
npm http GET https://registry.npmjs.org/depd
npm http GET https://registry.npmjs.org/iconv-lite/0.4.6
npm http GET https://registry.npmjs.org/on-finished
npm http GET https://registry.npmjs.org/media-typer/0.3.0
npm http GET https://registry.npmjs.org/qs/2.3.3
npm http GET https://registry.npmjs.org/raw-body/1.3.2
npm http GET https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/engine.io/1.5.2
npm http GET https://registry.npmjs.org/socket.io-parser/2.2.4
npm http GET https://registry.npmjs.org/socket.io-client/1.3.6
npm http GET https://registry.npmjs.org/socket.io-adapter/0.3.1
npm http GET https://registry.npmjs.org/has-binary-data/0.1.3
npm http GET https://registry.npmjs.org/debug/2.1.0
npm http GET https://registry.npmjs.org/array-flatten/1.0.0
npm http GET https://registry.npmjs.org/void-elements/1.0.0
npm http GET https://registry.npmjs.org/vcss/0.1.1
npm http GET https://registry.npmjs.org/qs/1.2.0
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/mime/1.2.11
npm http GET https://registry.npmjs.org/component-emitter/1.1.2
npm http GET https://registry.npmjs.org/methods/1.0.1
npm http GET https://registry.npmjs.org/cookiejar/2.0.1
npm http GET https://registry.npmjs.org/reduce-component/1.0.1
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/form-data/0.1.3
npm http GET https://registry.npmjs.org/readable-stream/1.0.27-1
npm http GET https://registry.npmjs.org/accepts
npm http GET https://registry.npmjs.org/content-disposition/0.5.0
npm http GET https://registry.npmjs.org/cookie-signature/1.0.5
npm http GET https://registry.npmjs.org/etag
npm http GET https://registry.npmjs.org/escape-html/1.0.1
npm http GET https://registry.npmjs.org/finalhandler/0.3.3
npm http GET https://registry.npmjs.org/fresh/0.2.4
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/path-to-regexp/0.1.3
npm http GET https://registry.npmjs.org/proxy-addr
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/send/0.11.0
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/vary
npm http GET https://registry.npmjs.org/cookie/0.1.2
npm http GET https://registry.npmjs.org/merge-descriptors/0.0.2
npm http GET https://registry.npmjs.org/utils-merge/1.0.0
npm http 304 https://registry.npmjs.org/bytes/1.0.0
npm http 304 https://registry.npmjs.org/iconv-lite/0.4.6
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/depd
npm http 304 https://registry.npmjs.org/on-finished
npm http 304 https://registry.npmjs.org/qs/2.3.3
npm http 304 https://registry.npmjs.org/raw-body/1.3.2
npm http 304 https://registry.npmjs.org/engine.io/1.5.2
npm http 304 https://registry.npmjs.org/type-is
npm http 304 https://registry.npmjs.org/socket.io-parser/2.2.4
npm http 304 https://registry.npmjs.org/media-typer/0.3.0
npm http 304 https://registry.npmjs.org/socket.io-client/1.3.6
npm http 304 https://registry.npmjs.org/socket.io-adapter/0.3.1
npm http 304 https://registry.npmjs.org/has-binary-data/0.1.3
npm http 304 https://registry.npmjs.org/debug/2.1.0
npm http 304 https://registry.npmjs.org/array-flatten/1.0.0
npm http 304 https://registry.npmjs.org/void-elements/1.0.0
npm http 304 https://registry.npmjs.org/vcss/0.1.1
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm http 304 https://registry.npmjs.org/qs/1.2.0
npm http 304 https://registry.npmjs.org/mime/1.2.11
npm http 304 https://registry.npmjs.org/component-emitter/1.1.2
npm http 304 https://registry.npmjs.org/cookiejar/2.0.1
npm http 304 https://registry.npmjs.org/methods/1.0.1
npm http 304 https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/form-data/0.1.3
npm http 304 https://registry.npmjs.org/readable-stream/1.0.27-1
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.5
npm http 304 https://registry.npmjs.org/accepts
npm http 304 https://registry.npmjs.org/content-disposition/0.5.0
npm http 304 https://registry.npmjs.org/etag
npm http 304 https://registry.npmjs.org/escape-html/1.0.1
npm http 304 https://registry.npmjs.org/finalhandler/0.3.3
npm http 304 https://registry.npmjs.org/fresh/0.2.4
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/path-to-regexp/0.1.3
npm http 304 https://registry.npmjs.org/proxy-addr
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/send/0.11.0
npm http GET https://registry.npmjs.org/ee-first/1.1.0
npm http 304 https://registry.npmjs.org/vary
npm http 304 https://registry.npmjs.org/serve-static
npm http 304 https://registry.npmjs.org/cookie/0.1.2
npm http 304 https://registry.npmjs.org/merge-descriptors/0.0.2
npm http GET https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/utils-merge/1.0.0
npm http GET https://registry.npmjs.org/object-keys/1.0.1
npm http GET https://registry.npmjs.org/debug/1.0.2
npm http GET https://registry.npmjs.org/socket.io-parser/2.2.2
npm http 304 https://registry.npmjs.org/ee-first/1.1.0
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/socket.io-parser/2.2.2
npm http 304 https://registry.npmjs.org/object-keys/1.0.1
npm http 304 https://registry.npmjs.org/debug/1.0.2
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/crc/3.2.1
npm http GET https://registry.npmjs.org/forwarded
npm http GET https://registry.npmjs.org/ipaddr.js/1.0.5
npm http GET https://registry.npmjs.org/negotiator/0.5.3
npm http 304 https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/send/0.11.1
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/ipaddr.js/1.0.5
npm http GET https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/destroy/1.0.3
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/send/0.11.1
npm http 304 https://registry.npmjs.org/crc/3.2.1
npm http 304 https://registry.npmjs.org/destroy/1.0.3
npm http 304 https://registry.npmjs.org/forwarded
npm http GET https://registry.npmjs.org/ws/0.7.2
npm http GET https://registry.npmjs.org/engine.io-parser/1.2.1
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/debug/1.0.3
npm http GET https://registry.npmjs.org/benchmark/1.0.0
npm http GET https://registry.npmjs.org/debug/0.7.4
npm http GET https://registry.npmjs.org/json3/3.2.6
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/debug/1.0.3
npm http 304 https://registry.npmjs.org/benchmark/1.0.0
npm http 304 https://registry.npmjs.org/debug/0.7.4
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/json3/3.2.6
npm http 304 https://registry.npmjs.org/ws/0.7.2
npm http 304 https://registry.npmjs.org/engine.io-parser/1.2.1
npm http 304 https://registry.npmjs.org/negotiator/0.5.3
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/component-bind/1.0.0
npm http GET https://registry.npmjs.org/object-component/0.0.3
npm http GET https://registry.npmjs.org/has-binary/0.1.6
npm http GET https://registry.npmjs.org/indexof/0.0.1
npm http GET https://registry.npmjs.org/parseuri/0.0.2
npm http GET https://registry.npmjs.org/to-array/0.1.3
npm http GET https://registry.npmjs.org/backo2/1.0.2
npm http GET https://registry.npmjs.org/engine.io-client/1.5.2
npm http GET https://registry.npmjs.org/after/0.8.1
npm http GET https://registry.npmjs.org/arraybuffer.slice/0.0.6
npm http GET https://registry.npmjs.org/base64-arraybuffer/0.1.2
npm http GET https://registry.npmjs.org/blob/0.0.2
npm http GET https://registry.npmjs.org/has-binary/0.1.5
npm http GET https://registry.npmjs.org/utf8/2.0.0
npm http 304 https://registry.npmjs.org/component-bind/1.0.0
npm http 304 https://registry.npmjs.org/has-binary/0.1.6
npm http 304 https://registry.npmjs.org/object-component/0.0.3
npm http 304 https://registry.npmjs.org/indexof/0.0.1
npm http 304 https://registry.npmjs.org/parseuri/0.0.2
npm http 304 https://registry.npmjs.org/to-array/0.1.3
npm http 304 https://registry.npmjs.org/backo2/1.0.2
npm http 304 https://registry.npmjs.org/engine.io-client/1.5.2
npm http 304 https://registry.npmjs.org/after/0.8.1
npm http 304 https://registry.npmjs.org/arraybuffer.slice/0.0.6
npm http 304 https://registry.npmjs.org/base64-arraybuffer/0.1.2
npm http GET https://registry.npmjs.org/bufferutil
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/ultron
npm http GET https://registry.npmjs.org/utf-8-validate
npm http 304 https://registry.npmjs.org/blob/0.0.2
npm http 304 https://registry.npmjs.org/utf8/2.0.0
npm http 304 https://registry.npmjs.org/has-binary/0.1.5
npm http 304 https://registry.npmjs.org/ultron
npm http 304 https://registry.npmjs.org/bufferutil
npm http GET https://registry.npmjs.org/better-assert
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/better-assert
npm http GET https://registry.npmjs.org/component-inherit/0.0.3
npm http GET https://registry.npmjs.org/debug/1.0.4
npm http GET https://registry.npmjs.org/has-cors/1.0.3
npm http GET https://registry.npmjs.org/parsejson/0.0.1
npm http GET https://registry.npmjs.org/parseqs/0.0.2
npm http GET https://registry.npmjs.org/parseuri/0.0.4
npm http GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm http GET https://registry.npmjs.org/callsite/1.0.0
npm http 304 https://registry.npmjs.org/debug/1.0.4
npm http 304 https://registry.npmjs.org/component-inherit/0.0.3
npm http 304 https://registry.npmjs.org/has-cors/1.0.3
npm http 304 https://registry.npmjs.org/parsejson/0.0.1
npm http 304 https://registry.npmjs.org/parseqs/0.0.2
npm http 304 https://registry.npmjs.org/parseuri/0.0.4
npm http 304 https://registry.npmjs.org/callsite/1.0.0
npm http 304 https://registry.npmjs.org/utf-8-validate
npm http GET https://registry.npmjs.org/acorn-babel/0.11.1-37
npm http GET https://registry.npmjs.org/chokidar
npm http GET https://registry.npmjs.org/ast-types
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/convert-source-map
npm http GET https://registry.npmjs.org/core-js
npm http GET https://registry.npmjs.org/detect-indent
npm http GET https://registry.npmjs.org/estraverse
npm http GET https://registry.npmjs.org/fs-readdir-recursive
npm http GET https://registry.npmjs.org/esutils
npm http GET https://registry.npmjs.org/globals
npm http GET https://registry.npmjs.org/is-integer
npm http GET https://registry.npmjs.org/js-tokens/1.0.0
npm http GET https://registry.npmjs.org/leven
npm http GET https://registry.npmjs.org/line-numbers/0.2.0
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/output-file-sync
npm http GET https://registry.npmjs.org/path-is-absolute
npm http GET https://registry.npmjs.org/private
npm http GET https://registry.npmjs.org/regenerator-babel/0.8.13-2
npm http GET https://registry.npmjs.org/regexpu
npm http GET https://registry.npmjs.org/repeating
npm http GET https://registry.npmjs.org/slash
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/source-map-support
npm http GET https://registry.npmjs.org/to-fast-properties
npm http GET https://registry.npmjs.org/trim-right
npm http GET https://registry.npmjs.org/shebang-regex
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/chokidar
npm http 304 https://registry.npmjs.org/acorn-babel/0.11.1-37
npm http 304 https://registry.npmjs.org/convert-source-map
npm http 304 https://registry.npmjs.org/ast-types
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/detect-indent
npm http 304 https://registry.npmjs.org/estraverse
npm http 304 https://registry.npmjs.org/core-js
npm http 200 https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm http 304 https://registry.npmjs.org/fs-readdir-recursive
npm http 304 https://registry.npmjs.org/esutils
npm http 304 https://registry.npmjs.org/globals
npm http 304 https://registry.npmjs.org/is-integer
npm http 304 https://registry.npmjs.org/js-tokens/1.0.0
npm http 304 https://registry.npmjs.org/leven
npm http 304 https://registry.npmjs.org/line-numbers/0.2.0
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/output-file-sync
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/regenerator-babel/0.8.13-2
npm http 304 https://registry.npmjs.org/private
npm http 304 https://registry.npmjs.org/regexpu
npm http 304 https://registry.npmjs.org/repeating
npm http 304 https://registry.npmjs.org/slash
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/source-map-support
npm http 304 https://registry.npmjs.org/to-fast-properties
npm http 304 https://registry.npmjs.org/trim-right
npm http 304 https://registry.npmjs.org/shebang-regex
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/is-finite
npm http GET https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/left-pad/0.0.3
npm http GET https://registry.npmjs.org/fsevents
npm http GET https://registry.npmjs.org/readdirp
npm http GET https://registry.npmjs.org/async-each
npm http 304 https://registry.npmjs.org/is-finite
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/recast
npm http GET https://registry.npmjs.org/regjsgen
npm http GET https://registry.npmjs.org/regenerate
npm http GET https://registry.npmjs.org/regjsparser
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/left-pad/0.0.3
npm http 304 https://registry.npmjs.org/async-each
npm http 304 https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/readdirp
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/recast
npm http 304 https://registry.npmjs.org/regjsgen
npm http 304 https://registry.npmjs.org/regenerate
npm http 304 https://registry.npmjs.org/regjsparser
npm WARN optional dep failed, continuing fsevents@0.3.8
npm http GET https://registry.npmjs.org/number-is-nan
npm http GET https://registry.npmjs.org/ansi-regex
npm http GET https://github.com/component/global/archive/v2.0.1.tar.gz
npm http GET https://registry.npmjs.org/commoner
npm http GET https://registry.npmjs.org/through
npm http 304 https://registry.npmjs.org/number-is-nan
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/jsesc
npm http 304 https://registry.npmjs.org/commoner
npm http 304 https://registry.npmjs.org/through
npm http GET https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/jsesc

> utf-8-validate@1.1.0 install /usr/local/lib/node_modules/slackin/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

npm http GET https://registry.npmjs.org/source-map/0.1.32
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/source-map/0.1.32
npm http 200 https://github.com/component/global/archive/v2.0.1.tar.gz
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slackin/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/minimatch
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/graceful-fs
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/detective
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/ast-types/0.8.12
npm http GET https://registry.npmjs.org/esprima-fb

> bufferutil@1.1.0 install /usr/local/lib/node_modules/slackin/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/detective
npm http 304 https://registry.npmjs.org/esprima-fb
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/ast-types/0.8.12
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slackin/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing bufferutil@1.1.0
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/acorn
npm http GET https://registry.npmjs.org/defined
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/once

> utf-8-validate@1.1.0 install /usr/local/lib/node_modules/slackin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

npm http GET https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/acorn
npm http 304 https://registry.npmjs.org/defined
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/wrappy
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slackin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1

> bufferutil@1.1.0 install /usr/local/lib/node_modules/slackin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slackin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing bufferutil@1.1.0
/usr/local/bin/slackin -> /usr/local/lib/node_modules/slackin/bin/slackin

> slackin@0.7.3 postinstall /usr/local/lib/node_modules/slackin
> make

make: Nothing to be done for `all'.
slackin@0.7.3 /usr/local/lib/node_modules/slackin
├── email-regex@1.0.0
├── hostenv@1.0.1
├── commander@2.6.0
├── debug@2.1.1 (ms@0.6.2)
├── vd@0.1.0 (array-flatten@1.0.0, void-elements@1.0.0, vcss@0.1.1)
├── superagent@0.21.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@1.2.0, mime@1.2.11, readable-stream@1.0.27-1, form-data@0.1.3, formidable@1.0.14)
├── body-parser@1.10.2 (media-typer@0.3.0, bytes@1.0.0, raw-body@1.3.2, depd@1.0.1, on-finished@2.2.1, qs@2.3.3, type-is@1.5.7, iconv-lite@0.4.6)
├── opentype.js@0.4.4
├── express@4.11.0 (merge-descriptors@0.0.2, utils-merge@1.0.0, methods@1.1.1, fresh@0.2.4, cookie@0.1.2, escape-html@1.0.1, range-parser@1.0.3, vary@1.0.1, cookie-signature@1.0.5, finalhandler@0.3.3, media-typer@0.3.0, parseurl@1.3.0, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.1, on-finished@2.2.1, qs@2.3.3, etag@1.5.1, proxy-addr@1.0.10, send@0.11.0, serve-static@1.8.1, accepts@1.2.13, type-is@1.5.7)
├── socket.io@1.3.6 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.2, socket.io-client@1.3.6)
└── babel@4.7.1 (to-fast-properties@1.0.1, trim-right@1.0.1, slash@1.0.0, shebang-regex@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.2, leven@1.0.2, globals@6.4.1, private@0.1.6, esutils@1.1.6, estraverse@1.9.3, convert-source-map@0.5.1, js-tokens@1.0.0, line-numbers@0.2.0, ast-types@0.7.8, repeating@1.1.3, detect-indent@3.0.1, is-integer@1.0.6, chalk@1.1.1, source-map@0.4.4, output-file-sync@1.1.1, acorn-babel@0.11.1-37, chokidar@0.12.6, source-map-support@0.2.10, core-js@0.6.1, regexpu@1.3.0, lodash@3.10.1, regenerator-babel@0.8.13-2)

**Comment by jaygilmore** [comment]
This may be related to the fact that on Debian and Ubuntu you need to install node thusly: 
`apt-get install nodejs-legacy` vs the standard installation as there is a collision with another `node
