### ISSUE TITLE
Deploy to Azure is not working

### ISSUE THREAD

**Issue by fushnisoft** [rauchg/slackin#129]
Thanks for creating this BTW!

I thought I would give the deploy to azure a try but unfortunately it didn't work for me.
The log shows a bunch of errors but debugging that any further is a bit beyond me. 
Maybe @jpoon can make something of it?
https://gist.github.com/fushnisoft/028112c00347e1c137e3

**Comment by jpoon** [comment]
Hey! Thanks for trying this out.

Looks like its trying to deploy using the old build system (`make`). Can you try deploying using the `latest` option?

* Latest: deploy what's in the git repo (ie. uses gulp rather than make)
* Stable: deploys latest npm package which I suspect is a couple commits behind and still uses make.

**Comment by fushnisoft** [comment]
Yes, that did it.
In fact I tried that back when this was still a PR but it didn't work then. I figured I would wait until it was merged but this time only tried stable before adding the issue here.
Up and running now, many thanks. Nice work!

**Comment by jpoon** [comment]
Sweet! Glad to hear.

@rauchg, would you mind pushing a new NPM package with the gulp bits in order to get the `stable` deployment to work?

**Comment by rauchg** [comment]
@jpoon did you check `0.8.1`?

**Comment by jpoon** [comment]
Just tried deploying the `latest` option => 0.8.1 and it works.

As per @fushnisoft's logs, when he had tried deploying 0.7.3 was published on npm. 

```
    {
        "details_url": null,
        "id": "",
        "log_time": "2016-01-06T12:11:28.1396682Z",
        "message": "> slackin@0.7.3 postinstall d:\\home\\site\\wwwroot\\node_modules\\slackin",
        "type": 0
    },
```

**Comment by fushnisoft** [comment]
I also just tested a changing the SLACKIN_RELEASE from `latest` to `master` in azure and syncing the deployment. Works like a charm, on 0.8.1 now. Thanks!
