### ISSUE TITLE
sign in link generated is broken

### ISSUE THREAD

**Issue by Stoner19** [rauchg/slackin#140]
After build to OpenShift, it ends up pointing to https://xn--myslackteam-2p3dsa.slack.com/. I tried changing the `slack-invite.js` & `splash.js` files to the direct link, so it wasn't trying to call to `${org}.slack.com` but that didn't seem to fix the problem.

https://github.com/rauchg/slackin/blob/master/lib/splash.js#L45

It appears to me that its `${org}` that isn't being read properly, but I don't know how to fix that. 

Looks like it's specific to OpenShift, as deployment to Heroku and local servers seem to be just fine. Unsure about Azure though as I have not tested that.

**Comment by rauchg** [comment]
Maybe @balupton knows? I'm not familiar with OpenShift.

**Comment by balupton** [comment]
Ended up moving to heroku myself - as it seems heroku never actually bothered proceeding with the 8 hours of downtime a day for free dynos.

If https://github.com/rauchg/slackin/wiki/OpenShift isn't working, then that is as much help as I can provide.
