### ISSUE TITLE
URL path for slackin?

### ISSUE THREAD

**Issue by mjbrender** [rauchg/slackin#150]
I'm having some trouble with deploying my own version server with slackin. I used the docker image and have it running with my domain and API settings. I can't tell where the server is mounting. What would be my URL? 

Notes: 

* Spun up on Digital Ocean 
* Running Dockerfile provided in repo 
* passed in subdomain and api as parameters, which appeared to work: 

```
core@coreos-512mb-sfo1-01 ~/slackin $ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
01fee697b64f        8e6afcd6383a        "slackin evangelistco"   9 minutes ago       Up 9 minutes                            jolly_euclid
core@coreos-512mb-sfo1-01 ~/slackin $ docker logs 01fee697b64f
Mon Feb 22 2016 01:17:44 GMT+0000 (UTC) – fetching
Mon Feb 22 2016 01:17:45 GMT+0000 (UTC) – online 32, total 317 (+694ms)
Mon Feb 22 2016 01:17:50 GMT+0000 (UTC) – fetching
Mon Feb 22 2016 01:17:50 GMT+0000 (UTC) – online 31, total 317 (+663ms)
Mon Feb 22 2016 01:17:55 GMT+0000 (UTC) – fetching
Mon Feb 22 2016 01:17:56 GMT+0000 (UTC) – online 31, total 317 (+780ms)
```

Please point me in the right direction if I'm doing this totally wrong and thank you! I'm glad to write up instructions to put w/the Dockerfile for other people new to this.

**Comment by rauchg** [comment]
This looks great. But you don't seem to be launching the container with a port bound, thus it's inaccessible?
