### ISSUE TITLE
Redirecting already signed-up users works on master but not v0.8.2

### ISSUE THREAD

**Issue by laughinghan** [rauchg/slackin#157]
On v0.8.2, I get stuck on:
![image](https://cloud.githubusercontent.com/assets/225809/13371831/59f21dfc-dce4-11e5-92b8-af7f0bb6bbc0.png)

This appears to be because in #126, the branch of server code that instructs the client to perform a redirect [expects `.redirectUrl` on the "Already Invited" error object](https://github.com/rauchg/slackin/pull/126/files#diff-6d186b954a58d5bb740f73d84fe39073R124), but no such property is set [when the error object is thrown](https://github.com/rauchg/slackin/pull/126/files#diff-791c9eb7427e9bc03803e66f5da5c30bR35).

However, this has been fixed by #143 ([which checks for the error message rather than `.redirectUrl`](https://github.com/rauchg/slackin/pull/143/files#diff-6d186b954a58d5bb740f73d84fe39073L126)), so I've had to upgrade to the unreleased `master` branch. @rauchg, any chance you could release v0.8.3? (And while you're at it, include #153, #154, and #156, too? :D )

**Comment by laughinghan** [comment]
All those PRs have been merged into my `myfork` branch: https://github.com/rauchg/slackin/compare/master...laughinghan:myfork

Which in turn has been deployed to http://slackin.mathquill.com (see http://mathquill.com for an example of the large dialog in action)

**Comment by laughinghan** [comment]
(Also #161, while we're at it)

@rauchg I fixed the merge conflict in #156, anything blocking you from releasing v0.8.3?

**Comment by laughinghan** [comment]
@rauchg Now that they're all merged, ready to release v0.8.3 to fix all these problems?

**Comment by rauchg** [comment]
@laughinghan just did. Do you mind testing that it works well with Heroku button so I can bump the tag in the readme? Thank you!

**Comment by laughinghan** [comment]
Uh, it's not how I'm using it but sure, why not

Han

**Comment by rauchg** [comment]
oh! I thought you were. Feel free to test it with your architecture. `0.8.3` on npm

**Comment by laughinghan** [comment]
@rauchg Works great for me on my architecture!
