### ISSUE TITLE
Stuck on "Please Wait"

### ISSUE THREAD

**Issue by kchristidis** [rauchg/slackin#165]
After I pressing the "Get My Invite" button, I get a "Please Wait" button and that's all -- no invitation email ever comes to my inbox.

I am using a _test_ token for an admin account, [generated here](https://api.slack.com/docs/oauth-test-tokens).

What am I doing wrong? (Is it the fact that it's a test token?)

PS: Thanks for a neat project.

**Comment by paulofaria** [comment]
same here!

**Comment by sedzia** [comment]
I guess this is a fix for this problem https://github.com/rauchg/slackin/pull/164/commits/d6d9db70e2cad93d39a3c9c5f2cff5c6a344e121

**Comment by cycod3r** [comment]
On heroku I added the SLACK_CHANNELS setting key with a value, saved, deleted the value, saved. Worked until the instance went to sleep. Once it slept, I had to add a space, save, delete the space, works again until next sleep.

**Comment by kchristidis** [comment]
Thanks for the replies everyone. Adding a `channels` key-value pair seems to have fixed this.

**Comment by GeneticGenesis** [comment]
Hey, is there any chance of a release to npm with this fix in?

Cheers,

**Comment by julianadenauer** [comment]
Same problem here: how do we get this fix into npm?

**Comment by Zuse2k** [comment]
same here
