### ISSUE TITLE
Error when clicking 'get my invite'

### ISSUE THREAD

**Issue by crobinson42** [rauchg/slackin#169]
starting slackin with:

`slackin {my_team_name} xoxp-276xxx505139-xxxxxxxxx-xxxxxxx-4xxx0e3x5 -h localhost -p 3001`

When adding an email address and clicking 'get my invite', this message appears in the console:

`client.js:22 Uncaught TypeError: Cannot read property 'value' of undefined`

Screenshots:
https://www.dropbox.com/s/iq3lwmel0x7etmx/Screenshot%202016-03-18%2023.59.38.png?dl=0
https://www.dropbox.com/s/cjwokeaefkh8nw0/Screenshot%202016-03-18%2023.59.32.png?dl=0
https://www.dropbox.com/s/zmsroho719gwyyl/Screenshot%202016-03-18%2023.59.48.png?dl=0

node v4.4
npm v2.14

**Comment by nbolt** [comment]
same issue here

**Comment by timpritlove** [comment]
same here. going back to 0.8.1 brings up a syntax error. can't get login screen to work.

**Comment by funkhouserw** [comment]
Encountering this issue as well,  used the one-click heroku deploy link in the readme.  

Of possible note:  the first person to sign-up to this channel via slackin seems to have done so without any issues. All following attempts are resulting in errors.

**Comment by nbolt** [comment]
I'm using slackin on my own server and this change fixes the issue for me, if anyone else needs it in the meantime: http://hastebin.com/kowixofuja.js

**Comment by funkhouserw** [comment]
Worked fine for me. Thanks @nbolt !

**Comment by timpritlove** [comment]
Yes, the fix works for me too. Should be rolled in to a new release.

**Comment by skreutzberger** [comment]
I have the same issue with Slackin version 0.8.3 even after applying the fix which changes `var channel = form.elements['channel'];`to `var channel = form.elements['channel'] || {};` in the file `~/.npm-global/lib/node_modules/slackin/lib/assets/config.js`

When adding an email to the list the following error does still occur:

<img width="639" alt="screenshot 2016-05-12 at 10 04 46" src="https://cloud.githubusercontent.com/assets/564725/15207940/743ef18c-1829-11e6-893d-978aab2d3242.png">

**Comment by rauchg** [comment]
PRs welcome!

**Comment by skreutzberger** [comment]
Oh and where does Slackin log to? My above mentioned error (undefined value) was not visible in  Slackin console output on the server.

**Comment by maxnaude** [comment]
@nbolt thanks - that worked for me on 0.8.3
