### ISSUE TITLE
channel.value undefined

### ISSUE THREAD

**Issue by tanner0101** [rauchg/slackin#177]
I keep getting this error with `0.8.3`.

```
[Error] TypeError: undefined is not an object (evaluating 'channel.value')
    (anonymous function) (client.js:22)
```

**Comment by teone** [comment]
Same error here, downgrading to `0.6.0` worked for me...

**Comment by tannernelson** [comment]
I had to downgrade as well. q_q

**Comment by felicianotech** [comment]
The master branch has the fix for this. For some reason it just hasn't be deployed to NPM. I manually fixed it myself for the copy I have running on my server.

https://github.com/rauchg/slackin/blob/master/lib/assets/client.js#L22
