### ISSUE TITLE
Clearer docs about how to get token

### ISSUE THREAD

**Issue by mrmayfield** [rauchg/slackin#178]
`You can find your API token at api.slack.com/web – note that the user you use to generate the token must be an admin. You need to create a dedicated @slackin-inviter user (or similar), mark that user an admin, and use a token from that dedicated admin user.`

Maybe we want to add a bit about how it's a test token that we're looking for? I wasn't super clear if I was in the right place when I was there (eventually did get it to work though :) )

**Comment by laughinghan** [comment]
Do you think this would've helped? https://get.slack.help/hc/en-us/articles/215770388-Creating-and-regenerating-API-tokens

**Comment by mrmayfield** [comment]
Yeah for sure, it would have been a lot clearer. I just didn't know a 'test' token would give me actual permissions, I kinda thought it was for a sandbox model.

**Comment by thecodejunkie** [comment]
It's also worth noting that the test token is tied to the user account that generated it and the e-mail of said account will appear in the invite e-mail. Choose account accordingly

**Comment by mrmayfield** [comment]
+1
