### ISSUE TITLE
Heroku fails to build app

### ISSUE THREAD

**Issue by csu** [rauchg/slackin#18]
When I try to deploy with Heroku, I get:
> Build App
> There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

**Comment by csu** [comment]
Never mind! Tried a few more times and it worked eventually.

**Comment by csu** [comment]
It does crash though:
> Application Error
> An error occurred in the application and your page could not be served. Please try again in a few moments.
> 
> If you are the application owner, check your logs for details.

**Comment by jonbstrong** [comment]
yes, I'm seeing this too

**Comment by alhvi** [comment]
If you are seeing this message, you need to configure your env variables in Heroku 

>$ heroku config:add SLACK_API_TOKEN="YOUR_SLACK_API_TOKEN"
>$ heroku config:add SLACK_SUBDOMAIN="YOUR_SLACK_SUBDOMAIN"

**Comment by DannyShort** [comment]
I am getting the application error even though i have configured my vars in Heroku

**Comment by magicstone1412** [comment]
same problem here

**Comment by burtherman** [comment]
Same issue here

**Comment by chaitanya9899** [comment]
same problem
