### ISSUE TITLE
Popup position in firefox

### ISSUE THREAD

**Issue by crobinson42** [rauchg/slackin#182]
I'm experiencing an issue with the popup rendering at the top of the page when the snippet and iframe for slackin is located at the bottom of the page.

This issue is only experienced in Firefox.

**Comment by laughinghan** [comment]
Screenshot? Browser version? OS? User-agent string?

**Comment by laughinghan** [comment]
also, Slackin version?

**Comment by crobinson42** [comment]
You can view it with Firefox at www.therms.io

**Comment by crobinson42** [comment]
@laughinghan any thoughts?

**Comment by crobinson42** [comment]
This appears to only be affecting OSX Firefox (v42). It is not reproducible in mobile Firefox or Windows Firefox.

Gif recording: http://recordit.co/beDRvESpMK/gif/notify

**Comment by egid** [comment]
The issue here is that `document.body.scrollTop` isn't supported by Firefox - it always returns `0`.

Using `document.documentElement.foo` works just fine.

**Comment by crobinson42** [comment]
I see you added window.scrollY/X - This still doesn't fix the popup. rendering to the stop of the page

**Comment by egid** [comment]
@crobinson42 - interesting. It worked on our install. documentElement had chrome issues, but `window.scrollY` seemed to work cross-browser.

**Comment by crobinson42** [comment]
I just manually added those 2 lines, maybe I should try a new install. I’ll let you know. Thanks.
