### ISSUE TITLE
paid_team

### ISSUE THREAD

**Issue by CokkocZateki** [rauchg/slackin#192]
Hi

Im getting the same error as in #79 

Has a fix been made already or is there any workaround to it?

thank you

**Comment by jtatum** [comment]
As mentioned in #79, please list the options you're using. You cannot do single channel invites without paying for Slack. This is a Slack restriction and most of the time when this error comes up here, it's due to that.

**Comment by CokkocZateki** [comment]
Ah yes ofc. You have to have a paid sub. Thanks for that@jtatum
