### ISSUE TITLE
Passing PORT as both an CLI arg and environment variable fails to start slackin

### ISSUE THREAD

**Issue by alexpls** [rauchg/slackin#206]
This is due to an issue in the args library detailed here: https://github.com/leo/args/issues/21

This currently breaks heroku deploys (and most likely other deploys too).

**Comment by leo** [comment]
This issue has been fixed in version `v1.3.0` of [args](https://github.com/leo/args). IMHO, this issue can now be closed. But please vote for [this PR](https://github.com/rauchg/slackin/pull/208), so that the dependency gets updated! :blush:

**Comment by alexpls** [comment]
Cool! Happy to close the issue once #208 gets merged in to master.
