### ISSUE TITLE
Deploying to heroku does not work

### ISSUE THREAD

**Issue by dgollahon** [rauchg/slackin#221]
First of all, thanks for building this--I've found it useful. Unfortunately it seems like directly deploying to heroku does not work correctly.

It appears to be due to this [line](https://github.com/rauchg/slackin/blob/1f14de089b1d3db6d232d051bc3122e736ab98b5/bin/slackin#L5), which expects `dist/` to exist, but does not by default, since it is ignored from source control.

I was able to work around it, but it was pretty confusing when I first tried to setup the server. It would be great if you could fix this or, at least, provide a better warning when unable to access `dist/`.

Thanks!

**Comment by tonyedwardspz** [comment]
@dgollahon I'm having the same issue. How did you work around it?

**Comment by dgollahon** [comment]
@tonyedwardspz: yeah, just checked `dist/` into my copy of the repo and pushed that.

**Comment by niftylettuce** [comment]
You can use this if you need to in the meanwhile:

<https://heroku.com/deploy?template=https://github.com/niftylettuce/slackin/tree/master>

**Comment by zenspider** [comment]
Confirmed that @niftylettuce's branch works fine. This bug has caused a LOT of teeth gnashing. Thank you @niftylettuce for the help!

**Comment by duaneking** [comment]
When will this be fixed?

**Comment by productcampsg** [comment]
Thank you @niftylettuce! I had the Application Error page whenever I tried deploying to Heroku using the official branch. 

I'm getting a 404 on [http://slack.productcampsg.com/](http://slack.productcampsg.com/) but [https://productcampsg.herokuapp.com](http://productcampsg.herokuapp.com) shows the app. 

Something like [http://slack.mindtheproduct.com/](http://slack.mindtheproduct.com/) works. Does the Landing Page work for all of you 👀?

**Comment by niftylettuce** [comment]
@productcampsg it works for me - maybe your Heroku dyno needs to be upgraded to Hobby or have a server ping it occasionally to wake up

**Comment by aaalveee** [comment]
@niftylettuce's branch is crashing for me, shows "Application Error"

**Comment by KvalheimRacing** [comment]
@rauchg You guys should add in the readme that the Heroku slack domain adress _only requires the team specific adress_, not the entire slack adress. So where it stands `SLACK_SUBDOMAIN`, you should only write `myteamname`. You will get an H10 error code if you write `myteamname.slack.com`.
