### ISSUE TITLE
Demo in README is broken

### ISSUE THREAD

**Issue by IvanFon** [rauchg/slackin#301]
Trying to go to the [demo](https://slackin-spzhjhzdnp.now.sh/) linked in the README gives an error 404.

**Comment by rauchg** [comment]
Fixed! Accidentally deleted my deployment :D
Here's the permanent one: https://slackin.now.sh

**Comment by albinekb** [comment]
@rauchg https://github.com/zeit/now-cli/issues/491 😉 let's Implement that
