### ISSUE TITLE
Do we use legacy tokens? 

### ISSUE THREAD

**Issue by tbarn** [rauchg/slackin#317]
It seems like Slack has changed their API token process a bunch in the last year or so. 

Two questions:
1) Should we still be using legacy tokens?
2) If so, are there any known issues with creating new legacy tokens? I know it mentions using them only for testing and development now. I can't remember if it always said that.

**Comment by rikmendes** [comment]
I have managed to create a legacy token to run slackin on heroku and it worked : https://api.slack.com/custom-integrations/legacy-tokens

**Comment by tbarn** [comment]
Yeah, I've been running on legacy tokens for awhile. I might make a PR to update the docs about this so that people know the new language that Slack is using around this.

**Comment by eebbesen** [comment]
Do we use legacy tokens because there's no other way to do it? I tried creating a webapp and using that token but got 503s. I was thoroughly confused by the Slack API documentation because I'd hope that we'd have other token options and I couldn't get any but legacy for my user to work...

**Comment by whoshallsucceed** [comment]
> Do we use legacy tokens because there's no other way to do it? I tried creating a webapp and using that token but got 503s. I was thoroughly confused by the Slack API documentation because I'd hope that we'd have other token options and I couldn't get any but legacy for my user to work...

Same here. I'm taking a look in the code base to try to figure out what's possible as an alternative :3
