### ISSUE TITLE
Optional captcha

### ISSUE THREAD

**Issue by KrzysztofMadejski** [rauchg/slackin#352]
Since running Slackin we had no problems with fake accounts and spam. It would be cool if captcha implemented in #311 was optional (if you don't specify keys it won't run).

**Comment by Daniel15** [comment]
> we had no problems with fake accounts and spam

You will eventually, once bots discover the page and spam it. The worst part is that Slack blocks you from sending out invites once you reach a certain number of pending invites 😃

**Comment by KrzysztofMadejski** [comment]
Better safe then! Thanks for looking into that :)
