### ISSUE TITLE
Single channel guest

### ISSUE THREAD

**Issue by karolispx** [rauchg/slackin#374]
Hi guys, 

I can't figure what's the proper way to invite people to a single channel as guests? We got 16 paid members in our workspace which should allow 80 single channel guests. I've modified package.json and added SLACK_CHANNELS to the "env" - once I run 'now' - it goes past the channel setting. 

I've ran 'now', then modified the package.json file and ran 'now' again, if that makes any difference.

Am I doing anything wrong?

Thanks!

**Comment by karolispx** [comment]
Did the same with heroku, specified channel name on set up, with and without # - no difference. 

Anyone?

**Comment by karolispx** [comment]
Anyone?

**Comment by kussberg** [comment]
@karolispx did you find a fix?

**Comment by karolispx** [comment]
> @karolispx did you find a fix?

@kussberg no we didn't, from what I remember we moved onto something else.
