### ISSUE TITLE
Can't deploy: Error ENOTFOUND

### ISSUE THREAD

**Issue by serranoarevalo** [rauchg/slackin#376]
Can't deploy this.

I get a cryptic error message saying: 

```bash
Sun Jul 15 2018 22:19:18 GMT+0000 (UTC) – fetching
> [0] events.js:183
> [0]       throw er; // Unhandled 'error' event
> [0]       ^
> [0]
> [0] Error: getaddrinfo ENOTFOUND HB1iBOkiV3PKDlmNp2ip5eS1
```

How to fix this?

Thanks a lot!

**Comment by dmoskovtsov** [comment]
HI. I'm having the same issue. Did anyone manage to resolve it?

**Comment by serranoarevalo** [comment]
Hi, I did, I had to manually modify the code, I changed bin/slackin to bin/slacking.js, I changed the start  scripts on package.json to
````json
"scripts": {
    "start": "cd bin && node slackin"
  }
````
I removed the post-install and build commands because for some reason they were executed on the server but the start command will never be called so I had to remove them.

Before you upload make sure that you have built the code (running gulp) and don't forget to include the 'dist' folder on the now.sh, files since there is no more 'build' command anymore.

```json
"now": {
    "type": "npm",
    "files": [
      "bin",
      "lib",
      "dist",
      "gulpfile.babel.js"
    ],
```

**Comment by kawallis** [comment]
I'm still getting same issue even after following above any other solutions ?

**Comment by serranoarevalo** [comment]
I forgot to meantion that i deleted everything on the slackin.js and only left:

````js
slackin(flags).listen(port, hostname, function(err) {
  if (err) throw err;
  if (!flags.silent)
    console.log("%s – listening on %s:%d", new Date(), hostname, port);
});
````

Of course I added the keys into the flags object.

**Comment by allmarkedup** [comment]
I'm having this same issue. I've previously deployed it on Now with no problems but something must have changed since then. If anyone else has ideas on how to get it working again it'd be much appreciated!
