### ISSUE TITLE
Error: Not a permitted channel

### ISSUE THREAD

**Issue by MoOx** [rauchg/slackin#63]
![screen shot 2015-06-08 at 15 05 37](https://cloud.githubusercontent.com/assets/157534/8035326/e1c6e678-0def-11e5-900a-65758c077f62.png)

I initially created an #fr channel & during the heroku deploy I specified this channel.
After that all try to get an invite return this error.

I tried to change back to #general on heroku, same error.

Any idea ?

**Comment by MoOx** [comment]
Ok it seems I didn't read enough. It was a free account. Sorry for the noize

>SLACK_CHANNEL
> Name of a single guest channel to invite them to (leave blank for a normal, all-channel invite). In order to make this work, you have to have a paid account. You'll only be able to invite as many people as your number of paying members times 5.

**Comment by patricknowlan** [comment]
I actually think we should re-open this issue. I get this message when trying to sign up a "single channel user" on a paid slack account. I am not able to get the automated heroku deploy version to invite users successfully. My guess is it has something to do with the config var SLACK_CHANNEL being deprecated  and the heroku build still prompts users to enter it. Do we now have to use SLACK_CHANNELS var? I tried both from the heroku settings dashboard and had no success.

**Comment by mlissner** [comment]
We have Slack for Non-profits set up and are running into this too, as indicated in 18f/slackin#5. Slack for non-profits should be the same as paid slack. 

I provided more details in the other issue, but when I look at the site, it appears correctly in the text. But if I look at the POST request, it says `channel=null`.

I've tried both SLACK_CHANNEL and SLACK_CHANNELS.

**Comment by mlissner** [comment]
Looks like something is up with comma splitting. I changed my SLACK_CHANNELS variable to have only one item with a trailing comma and things began working:

    public-chat,

**Comment by antwonlee** [comment]
@mlissner that doesn't seem to work....

**Comment by gkop** [comment]
This is being tracked in https://github.com/rauchg/slackin/issues/77 (I believe they are duplicate issues)

**Comment by MoOx** [comment]
This issue is already closed.

**Comment by gkop** [comment]
Naturally, but it folks may still stumble upon it in search results. For example, @antwonlee above ^^.
