### ISSUE TITLE
Assign to subdomain

### ISSUE THREAD

**Issue by PhillippOhlandt** [rauchg/slackin#64]
Hello,

its not clear how I can assign a subdomain to the running nodejs process so I have the landing page on the subdomain.

**Comment by Burstaholic** [comment]
I'd suggest a web server like Nginx for reverse proxy.

**Comment by ericlathrop** [comment]
@PhillippOhlandt I used nginx to forward incoming requests on a specific subdomain only to the slackin port. [Here's an example of my nginx config.](https://github.com/louisvilleio/louisville.io-ansible/blob/9458c778ece96085831025b60ba3bd77db6f10a8/roles/web/files/slackin.louisville.io.conf)

**Comment by PhillippOhlandt** [comment]
@ericlathrop Ah thanks, will try it out =)
