### ISSUE TITLE
"paid_teams_only"

### ISSUE THREAD

**Issue by Pana** [rauchg/slackin#79]
Can not invite, get above message, for a free account

**Comment by jtatum** [comment]
What options are you using? Only paid teams support single channel invites, for instance.

**Comment by Pana** [comment]
Thanks, this is the problems, it's ok now

**Comment by NurdTurd** [comment]
I've added more channels, but I still get the `paid_teams_only` issue. Any ideas?

**Comment by jtatum** [comment]
Please list the options you're using.

**Comment by CokkocZateki** [comment]
i get the same issue. has any workarounds come up?

**Comment by jtatum** [comment]
@CokkocZateki - please list the options you're using.

**Comment by bojanrajkovic** [comment]
I'm having this same issue with a free team. Here's the options I'm using (deployed to Azure): 
![image](https://cloud.githubusercontent.com/assets/110747/15341684/293d44de-1c5e-11e6-87bb-0551975468bc.png)

I was under the impression `SLACK_CHANNELS` was the way to go about *not* using single-channel guests.

**Comment by jtatum** [comment]
@bojanrajkovic as mentioned in the readme, specifying channels enables single channel mode.
